In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [11]:
input_data = pd.read_csv('training_data.csv')
input_data

,hour_of_day,day_of_week,month,holiday,weekday,summertime,temp,dew,humidity,precip,snow,snowdepth,windspeed,cloudcover,visibility,increase_stock
0,5,5,1,0,0,0,-7.2,-15.0,53.68,0.000,0,0.0,16.3,31.6,16.0,low_bike_demand
1,21,4,1,0,1,0,-1.3,-12.8,40.97,0.000,0,0.0,23.9,85.7,16.0,low_bike_demand
2,21,3,8,0,1,1,26.9,21.8,73.39,0.000,0,0.0,0.0,81.1,16.0,low_bike_demand
3,1,6,1,0,0,0,3.1,-4.0,59.74,0.000,0,0.0,19.2,0.0,16.0,low_bike_demand
4,17,0,3,0,1,0,11.7,-11.4,18.71,0.000,0,0.0,10.5,44.6,16.0,low_bike_demand
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1595,3,5,6,0,0,1,21.5,19.4,87.68,0.000,0,0.0,10.6,24.4,16.0,low_bike_demand
1596,14,0,6,0,1,1,23.2,20.1,82.43,2.217,0,0.0,9.8,92.1,10.4,low_bike_demand
1597,13,0,3,0,1,1,13.9,-2.2,32.93,0.000,0,2.0,18.2,79.3,16.0,low_bike_demand
1598,14,5,3,0,0,1,11.7,-9.3,22.09,0.000,0,0.0,5.8,24.4,16.0,high_bike_demand
1599,22,6,2,0,0,0,4.2,1.7,84.11,1.081,0,0.0,21.9,97.4,16.0,low_bike_demand

In [12]:
input_data.describe()

,hour_of_day,day_of_week,month,holiday,weekday,summertime,temp,dew,humidity,precip,snow,snowdepth,windspeed,cloudcover,visibility
count,1600.00000,1600.000000,1600.000000,1600.000000,1600.000000,1600.00000,1600.000000,1600.000000,1600.000000,1600.000000,1600.0,1600.000000,1600.000000,1600.000000,1600.000000
mean,11.37125,3.022500,6.468750,0.033125,0.710000,0.64375,15.210313,7.750750,63.927844,0.122042,0.0,0.042713,13.082500,64.322375,15.344125
std,6.94837,2.012965,3.454741,0.179019,0.453904,0.47904,9.264785,10.026459,19.079419,0.920600,0.0,0.421198,7.756652,32.748869,2.323737
min,0.00000,0.000000,1.000000,0.000000,0.000000,0.00000,-9.100000,-18.400000,15.850000,0.000000,0.0,0.000000,0.000000,0.000000,0.100000
25%,5.00000,1.000000,3.000000,0.000000,0.000000,0.00000,7.700000,-0.800000,47.845000,0.000000,0.0,0.000000,7.500000,28.800000,16.000000
50%,12.00000,3.000000,6.000000,0.000000,1.000000,1.00000,15.500000,8.300000,65.175000,0.000000,0.0,0.000000,12.300000,79.300000,16.000000
75%,17.00000,5.000000,9.000000,0.000000,1.000000,1.00000,23.200000,16.800000,79.955000,0.000000,0.0,0.000000,17.600000,92.800000,16.000000
max,23.00000,6.000000,12.000000,1.000000,1.000000,1.00000,35.600000,24.300000,99.890000,25.871000,0.0,6.710000,43.800000,100.000000,16.000000

In [18]:
# Create a new column 'increase_stock_binary' and map the values to low_bike_demand = 0 and high_bike_demand = 1
input_data_binary = input_data.copy() 
input_data_binary['increase_stock_binary'] = input_data_binary['increase_stock'].map({'low_bike_demand': 0, 'high_bike_demand': 1})

# Drop the original 'increase_stock' column if you no longer need it
input_data_binary.drop('increase_stock', axis=1, inplace=True)

input_data_binary

,hour_of_day,day_of_week,month,holiday,weekday,summertime,temp,dew,humidity,precip,snow,snowdepth,windspeed,cloudcover,visibility,increase_stock_binary
0,5,5,1,0,0,0,-7.2,-15.0,53.68,0.000,0,0.0,16.3,31.6,16.0,0
1,21,4,1,0,1,0,-1.3,-12.8,40.97,0.000,0,0.0,23.9,85.7,16.0,0
2,21,3,8,0,1,1,26.9,21.8,73.39,0.000,0,0.0,0.0,81.1,16.0,0
3,1,6,1,0,0,0,3.1,-4.0,59.74,0.000,0,0.0,19.2,0.0,16.0,0
4,17,0,3,0,1,0,11.7,-11.4,18.71,0.000,0,0.0,10.5,44.6,16.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1595,3,5,6,0,0,1,21.5,19.4,87.68,0.000,0,0.0,10.6,24.4,16.0,0
1596,14,0,6,0,1,1,23.2,20.1,82.43,2.217,0,0.0,9.8,92.1,10.4,0
1597,13,0,3,0,1,1,13.9,-2.2,32.93,0.000,0,2.0,18.2,79.3,16.0,0
1598,14,5,3,0,0,1,11.7,-9.3,22.09,0.000,0,0.0,5.8,24.4,16.0,1
1599,22,6,2,0,0,0,4.2,1.7,84.11,1.081,0,0.0,21.9,97.4,16.0,0

In [26]:
# Labels are the values we want to predict
labels_2_predict = np.array(input_data_binary['increase_stock_binary'])

# Romve column we want to predict
input_data_drop_stock = input_data_binary.drop('increase_stock_binary', axis = 1)

# Saving column names for later use
input_data_drop_stock_list = list(input_data_drop_stock.columns)

# Convert to numpy array
input_data_drop_stock = np.array(input_data_drop_stock)

In [103]:
# Using Skicit-learn to split data into training and testing sets
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets, random state is choosen to be able to reproduce result. Remove for more randomness
training_data, test_data, training_predict, test_predict = train_test_split(input_data_drop_stock, labels_2_predict, test_size = 0.10)

# Import the model we are using
from sklearn.ensemble import RandomForestClassifier

# Instantiate model with 1000 decision trees more trees gives better model but at the cost of more computational power 
# (the amount of data points will affect what value is good for n_estimators), 
# random_state is also choosen for reproduceability.
Skogen = RandomForestClassifier(n_estimators = 1000)

# Train the model on training data
Skogen.fit(training_data, training_predict)

# Use model on test_data to check validity
model_prediction = Skogen.predict(test_data)

In [104]:
#Correct prediction by the modell as a procentage

from sklearn.metrics import accuracy_score
accuracy = accuracy_score(test_predict, model_prediction)
print(f"Accuracy: {accuracy}")

Accuracy: 0.89375

In [105]:
#Precision is a measurement of how correct the prediction is, if the model predicts 1 how likely is it that the correct answear is 1
#Precision is calculated with: True positive / (True positive + False positive)

#Recal is a measurement of how good the model is at captureing all positive instances, for example how good is the modell at finding all 0
#Recal is calcultaed with: True positive / (True positive + False Negative)

#F1 is a harmonic mean between precision and recal, that is usefull when the class distribution is very unewen such as in our case where there are alot more 0 than 1.
#F1 is calculated with: 2 * Precision * Recall / (Precision + Recall)

#Support is to show how many of each instance there is
#Accuracy is the correct predicion by the modell as a procentage
#Macro average, average over Precision, Recal, and F1
#Weighted average, average over Precision, Recal and F1 with weighted values takeing in to acount the amount of datapoints in each class (0 or 1)



from sklearn.metrics import classification_report
print("Classification Report:")
print(classification_report(test_predict, model_prediction))

Classification Report:
              precision    recall  f1-score   support

           0       0.92      0.96      0.94       139
           1       0.62      0.48      0.54        21

    accuracy                           0.89       160
   macro avg       0.77      0.72      0.74       160
weighted avg       0.88      0.89      0.89       160

In [106]:
#Confusion matrix displayes amount of, True positiv (topleft), False positiv (bottom left), False negative (top right), True negative (bottom left)


from sklearn.metrics import confusion_matrix
cm = confusion_matrix(test_predict, model_prediction)
print("Confusion Matrix:")
print(cm)

Confusion Matrix:
[[133   6]
 [ 11  10]]